import java.sql.*;
import javax.swing.*;
import java.time.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abiyoga Dhaniswara
 */
public class HomePageFrame extends javax.swing.JFrame{
    private final int Ekonomi = 20000;
    private final int Bisnis = 50000;
    private final int Eksekutif = 70000;
    private final int IdAccount;
    private String NamaLengkap;
    LocalDate currentDate = LocalDate.now();
    private ArrayList<String> listKota = Database.getKota();
    /**
     * Creates new form HomePageFrame
     * @param IdAccount
     */
    public HomePageFrame(int IdAccount) {
        initComponents();
        TotalHarga.setEditable(false);
        RincianPembelian.setEditable(false);
        this.IdAccount = IdAccount;
        Dashboard.setText("WELCOME "+this.getNamaLengkap()+"!");
        setKota();
        setJadwal();
        updateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JenisKereta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ButtonBeli = new javax.swing.JButton();
        KotaAsal = new javax.swing.JComboBox<>();
        KotaTujuan = new javax.swing.JComboBox<>();
        JumlahBeli = new javax.swing.JTextField();
        PilihTanggal = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PilihJam = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TotalHarga = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        HistoryPembelian = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RincianPembelian = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Beli Tiket Kereta"));

        jLabel2.setText("Kota Asal");

        jLabel3.setText("Kota Tujuan");

        jLabel4.setText("Jenis Kereta");

        JenisKereta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kereta", "Ekonomi", "Bisnis", "Eksekutif" }));
        JenisKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKeretaActionPerformed(evt);
            }
        });
        JenisKereta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JenisKeretaKeyReleased(evt);
            }
        });

        jLabel5.setText("Jumlah Beli");

        ButtonBeli.setText("Beli");
        ButtonBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBeliActionPerformed(evt);
            }
        });

        KotaAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kota Asal" }));
        KotaAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotaAsalActionPerformed(evt);
            }
        });
        KotaAsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KotaAsalKeyReleased(evt);
            }
        });

        KotaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kota Tujuan" }));
        KotaTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotaTujuanActionPerformed(evt);
            }
        });
        KotaTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KotaTujuanKeyReleased(evt);
            }
        });

        JumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBeliActionPerformed(evt);
            }
        });
        JumlahBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JumlahBeliKeyReleased(evt);
            }
        });

        PilihTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tanggal" }));

        jLabel1.setText("Pilih Tanggal");

        jLabel8.setText("Pilih Jam");

        PilihJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jam" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PilihTanggal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JenisKereta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KotaAsal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KotaTujuan, 0, 304, Short.MAX_VALUE)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PilihJam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ButtonBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KotaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(KotaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PilihTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PilihJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(ButtonBeli)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Harga");

        jLabel7.setText("Rp. ");

        TotalHarga.setBackground(new java.awt.Color(255, 255, 102));
        TotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaActionPerformed(evt);
            }
        });
        TotalHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TotalHargaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("History Pembelian"));

        HistoryPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal Pembelian", "Tujuan", "Tanggal", "Jumlah Tiket", "Total Harga"
            }
        ));
        jScrollPane3.setViewportView(HistoryPembelian);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Rincian Pembelian"));

        RincianPembelian.setColumns(20);
        RincianPembelian.setRows(5);
        jScrollPane2.setViewportView(RincianPembelian);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
        );

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setKota(){
        for (String i : listKota){
            KotaAsal.addItem(i);
            KotaTujuan.addItem(i);
        }
    }
    
    private String getNamaLengkap(){
        String sql = "SELECT Nama_Lengkap FROM Account WHERE ID_Account = ?";
        try(Connection conn = Database.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql)){
            pstmt.setInt(1,this.IdAccount);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()){
                NamaLengkap = rs.getString("Nama_Lengkap");
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        return NamaLengkap;
    }
    
    private void setJadwal(){
        Random rand = new Random();
        LocalTime currentTime = LocalTime.now();
        for (int j = 0; j < 3;j++){
            String tanggal = currentDate.plusDays(j).toString();
            PilihTanggal.addItem(tanggal);
        }
        for (int i = 0; i < 2;i++){
            int randHour = currentTime.plusHours(rand.nextInt(24)).getHour();
            int randMin = currentTime.plusMinutes(rand.nextInt(60)).getMinute();
            PilihJam.addItem(String.valueOf(randHour)+":"+randMin);
        }
    }
    
    private void updateTable(){
        DefaultTableModel model = (DefaultTableModel)HistoryPembelian.getModel();
        while(model.getRowCount()>0){
            model.removeRow(0);
        }
        String sqlSelect = "SELECT Kota_Asal,Kota_Tujuan,Jadwal,Jumlah_Beli,Total_Harga FROM Transaksi WHERE ID_Account = ?";
            try(Connection conn = Database.getConnection();
                    PreparedStatement pstmt = conn.prepareStatement(sqlSelect)){
                pstmt.setInt(1,this.IdAccount);
                ResultSet rs = pstmt.executeQuery();
                while(rs.next()){
                    model.addRow(new Object[]{
                        getNamaLengkap(),
                        currentDate.toString(),
                        rs.getString("Kota_Asal")+" - "+rs.getString("Kota_Tujuan"),
                        rs.getString("Jadwal"),
                        rs.getString("Jumlah_Beli"),
                        rs.getString("Total_Harga"),
                    });
                }  
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }
    
    private void verifyTransaction(){
        if (JumlahBeli.getText().equals("")){
            TotalHarga.setText("");
        } else if (JumlahBeli.getText().matches("\\d+")){
            if (listKota.contains(KotaAsal.getSelectedItem()) && listKota.contains(KotaTujuan.getSelectedItem()) && JenisKereta.getSelectedItem().equals("Ekonomi")){
                int harga = Math.abs(listKota.indexOf(KotaAsal.getSelectedItem())-listKota.indexOf(KotaTujuan.getSelectedItem()));
                TotalHarga.setText(String.valueOf((harga*Ekonomi)*Integer.parseInt(JumlahBeli.getText())));
            }
            else if (listKota.contains(KotaAsal.getSelectedItem()) && listKota.contains(KotaTujuan.getSelectedItem()) && JenisKereta.getSelectedItem().equals("Bisnis")){
                int harga = Math.abs(listKota.indexOf(KotaAsal.getSelectedItem())-listKota.indexOf(KotaTujuan.getSelectedItem()));
                TotalHarga.setText(String.valueOf((harga*Bisnis)*Integer.parseInt(JumlahBeli.getText())));
            }
            else if (listKota.contains(KotaAsal.getSelectedItem()) && listKota.contains(KotaTujuan.getSelectedItem()) && JenisKereta.getSelectedItem().equals("Eksekutif")){
                int harga = Math.abs(listKota.indexOf(KotaAsal.getSelectedItem())-listKota.indexOf(KotaTujuan.getSelectedItem()));
                TotalHarga.setText(String.valueOf((harga*Eksekutif)*Integer.parseInt(JumlahBeli.getText())));
            }
        }
        else{
            TotalHarga.setText("");
        }
    }
    
    private void ButtonBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBeliActionPerformed
        // TODO add your handling code here:
        try{
            if(KotaAsal.getSelectedItem().equals(KotaTujuan.getSelectedItem())){
                JOptionPane.showMessageDialog(this,"Kota Tidak Boleh Sama!");
            }
            else if (JumlahBeli.getText().matches("\\d+")){
                if (!PilihJam.getSelectedItem().equals("PilihJam") && !KotaAsal.getSelectedItem().equals("Pilih Kota Asal") && !KotaTujuan.getSelectedItem().equals("Pilih Kota Tujuan") && !JenisKereta.getSelectedItem().equals("Pilih Jenis Kereta") && !PilihTanggal.getSelectedItem().equals("Pilih Tanggal") && !PilihJam.getSelectedItem().equals("Pilih Jam") && (Integer.parseInt(JumlahBeli.getText())>0)){
                    String sql = "INSERT INTO Transaksi VALUES (null,?,?,?,?,?,?,?)";
                    try(Connection conn = Database.getConnection();
                            PreparedStatement pstmt = conn.prepareStatement(sql)){
                        pstmt.setInt(1,this.IdAccount);
                        pstmt.setString(2,KotaAsal.getSelectedItem().toString());
                        pstmt.setString(3,KotaTujuan.getSelectedItem().toString());
                        pstmt.setString(4,JenisKereta.getSelectedItem().toString());
                        pstmt.setString(5,PilihTanggal.getSelectedItem().toString()+" - "+PilihJam.getSelectedItem().toString());
                        pstmt.setInt(6,Integer.parseInt(JumlahBeli.getText()));
                        pstmt.setInt(7,Integer.parseInt(TotalHarga.getText()));
                        pstmt.executeUpdate();
                    }catch (SQLException e){
                        JOptionPane.showMessageDialog(this,e.getMessage());
                    }
                    RincianPembelian.setText("Nama: "+getNamaLengkap()+"\nTujuan: "+KotaAsal.getSelectedItem()+" - "+KotaTujuan.getSelectedItem()+"\nJadwal: "+PilihTanggal.getSelectedItem()+"\nJam: "+PilihJam.getSelectedItem()+"\nTotal Tiket: "+JumlahBeli.getText()+"\nTotal Harga: "+TotalHarga.getText());
                    updateTable();
                    //Clear Selection
                    KotaAsal.setSelectedItem("Pilih Kota Asal");
                    KotaTujuan.setSelectedItem("Pilih Kota Tujuan");
                    JenisKereta.setSelectedItem("Pilih Jenis Kereta");
                    PilihTanggal.setSelectedItem("Pilih Tanggal");
                    PilihJam.setSelectedItem("Pilih Jam");
                    JumlahBeli.setText(null);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Lengkapi Data!");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Jumlah beli harus angka!");
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,"Lengkapi Data!");
        }
    }//GEN-LAST:event_ButtonBeliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginFrame Login = new LoginFrame();
        Login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void JenisKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKeretaActionPerformed
        // TODO add your handling code here:
        verifyTransaction();
    }//GEN-LAST:event_JenisKeretaActionPerformed

    private void KotaAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotaAsalActionPerformed
        // TODO add your handling code here:
        verifyTransaction();
    }//GEN-LAST:event_KotaAsalActionPerformed

    private void KotaTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotaTujuanActionPerformed
        // TODO add your handling code here:
        verifyTransaction();
    }//GEN-LAST:event_KotaTujuanActionPerformed

    private void JumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBeliActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_JumlahBeliActionPerformed

    private void TotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaActionPerformed

    private void JumlahBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBeliKeyReleased
        // TODO add your handling code here:
        verifyTransaction();
    }//GEN-LAST:event_JumlahBeliKeyReleased

    private void TotalHargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalHargaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaKeyReleased

    private void KotaAsalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KotaAsalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_KotaAsalKeyReleased

    private void KotaTujuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KotaTujuanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_KotaTujuanKeyReleased

    private void JenisKeretaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JenisKeretaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKeretaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HomePageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBeli;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JTable HistoryPembelian;
    private javax.swing.JComboBox<String> JenisKereta;
    private javax.swing.JTextField JumlahBeli;
    private javax.swing.JComboBox<String> KotaAsal;
    private javax.swing.JComboBox<String> KotaTujuan;
    private javax.swing.JComboBox<String> PilihJam;
    private javax.swing.JComboBox<String> PilihTanggal;
    private javax.swing.JTextArea RincianPembelian;
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
